//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctors_WebForum.Models.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LikePost
    {
        public int Id { get; set; }
        public Nullable<bool> StatusLike { get; set; }
        public int Post_ID { get; set; }
        public int Doctor_ID { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
