//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctors_WebForum.Models.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReplyComment
    {
        public int Id { get; set; }
        public string CommentContent { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public int Comment_ID { get; set; }
        public int Doctor_ID { get; set; }
    
        public virtual Comment Comment { get; set; }
    }
}
